### ISSUE TITLE
Clarify nltk data package dependencies in wiki

### ISSUE THREAD

**Issue by DavidMinarsch** [meyersbs/uncertainty#3]
import nltk
# for the current Classifier to load
nltk.download('treebank')
nltk.download('conll2000')
nltk.download('wordnet')
# for the current Classifier to work for predictions
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

**Comment by meyersbs** [comment]
Good catch! I've updated the [Installation & Usage](https://github.com/meyersbs/uncertainty/wiki/Installation-&-Usage) page on the Wiki.

I've also added you under [Acknowledgements](https://github.com/meyersbs/uncertainty/wiki#-acknowledgements)!

**Comment by DavidMinarsch** [comment]
Glad to help with some minor tweaks; thanks to you for a great repo!
