### ISSUE TITLE
Give a working example when pypi package is used

### ISSUE THREAD

**Issue by DavidMinarsch** [meyersbs/uncertainty#4]
from uncertainty.classifier import Classifier

cls = Classifier()
cls.predict("I wonder if I am the walrus.")
# ['C', 'C', 'N', 'C', 'C', 'C', 'C', 'C']

cls = Classifier(binary=True)
cls.predict("I wonder if I am the walrus.")
# ['C', 'C', 'U', 'C', 'C', 'C', 'C', 'C']

cls = Classifier (granularity='sentence')
cls.predict("I wonder if I am the walrus.")
# N

cls = Classifier (granularity='sentence', binary=True)
cls.predict("I wonder if I am the walrus.")
# U

**Comment by meyersbs** [comment]
Thank you very much for your suggestion. I've updated the [Installation & Usage](https://github.com/meyersbs/uncertainty/wiki/Installation-&-Usage) page on the Wiki.
