### ISSUE TITLE
Classifier never outputs 'U'

### ISSUE THREAD

**Issue by lucas0** [meyersbs/uncertainty#6]
Used more than 1500 texts, averaging 400 words each and not a single U word was output by classifier. Seems that the classifier is not working, if it ever did.

![image](https://user-images.githubusercontent.com/717884/108056035-b0236d00-7048-11eb-992a-8ae93b6f8636.png)

**Comment by meyersbs** [comment]
It looks like you're using the code in multilabel mode; either you passed the `-m` flag on the command line or are not passing `binary=True` to `Classifer()` in the code. In multilabel mode, individual words will not be labeled with a generic `U`, but instead with a `C` for _certain_ or one of the four types of uncertainty:

- `E`: Epistemic - the proposition is possible (based on our knowledge of the universe), but its truth-value cannot be determined.
- `D`: Doxastic - the proposition is assumed to be true or false, but its truth-value cannot be determined.
- `I`: Investigation - the proposition is in the process of having its truth-value determined.
- `N`: Condition - the proposition is truth or false based on the truth-value of another proposition.

I see `N` and `E` a few times in your output, which is expected in multilabel. If you were to run the same command without the `-m` flag (or with `binary=True`), then it would only output `C` or `U`.

See the [wiki](https://github.com/meyersbs/uncertainty/wiki/Installation-&-Usage) for more information.
